"""Validation report generator — Markdown + JSON (Phase 1C.4).

Aggregates validator.ValidationResult + reviewer.ReviewResult into
a unified report with completeness %, ERROR/WARN/INFO summary.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import UTC, datetime

from server.reviewer import ReviewResult
from server.validator import Finding, ValidationResult


@dataclass
class FullReport:
    domain: str
    file_path: str
    row_count: int
    col_count: int
    completeness_pct: float
    validation: ValidationResult
    review: ReviewResult | None
    generated_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    @property
    def total_errors(self) -> int:
        n = self.validation.error_count
        if self.review:
            n += self.review.error_count
        return n

    @property
    def total_warnings(self) -> int:
        n = self.validation.warn_count
        if self.review:
            n += self.review.warn_count
        return n

    @property
    def total_info(self) -> int:
        n = self.validation.info_count
        if self.review:
            n += sum(1 for f in self.review.findings if f.severity == "INFO")
        return n

    @property
    def verdict(self) -> str:
        if self.total_errors > 0:
            return "FAIL"
        if self.total_warnings > 0:
            return "PASS_WITH_WARNINGS"
        return "PASS"


def generate_markdown(report: FullReport) -> str:
    """Generate a human-readable Markdown validation report."""
    lines: list[str] = []

    verdict_icon = {"FAIL": "!!!", "PASS_WITH_WARNINGS": "!!", "PASS": "OK"}
    icon = verdict_icon.get(report.verdict, "?")

    lines.append(f"# SDTM Validation Report — {report.domain}")
    lines.append("")
    lines.append(f"**Verdict: {report.verdict}** [{icon}]")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| File | `{report.file_path}` |")
    lines.append(f"| Domain | {report.domain} |")
    lines.append(f"| Rows | {report.row_count:,} |")
    lines.append(f"| Variables | {report.col_count} |")
    lines.append(f"| Req Completeness | {report.completeness_pct}% |")
    lines.append(f"| Errors | {report.total_errors} |")
    lines.append(f"| Warnings | {report.total_warnings} |")
    lines.append(f"| Info | {report.total_info} |")
    lines.append(f"| Generated | {report.generated_at} |")
    lines.append("")

    # ── Rule-based findings ─────────────────────────────────────────
    lines.append("## Rule-Based Validation")
    lines.append("")

    if not report.validation.findings:
        lines.append("No findings.")
    else:
        for sev in ("ERROR", "WARN", "INFO"):
            sev_findings = [f for f in report.validation.findings if f.severity == sev]
            if not sev_findings:
                continue
            lines.append(f"### {sev} ({len(sev_findings)})")
            lines.append("")
            for f in sev_findings:
                var_tag = f" `{f.variable}`" if f.variable else ""
                lines.append(f"- **[{f.rule}]**{var_tag}: {f.message}")
                if f.value_sample:
                    lines.append(f"  - Sample values: `{f.value_sample}`")
                if f.row_indices and len(f.row_indices) <= 10:
                    lines.append(f"  - Rows: {f.row_indices}")
            lines.append("")

    # ── Semantic review findings ────────────────────────────────────
    if report.review and report.review.findings:
        lines.append("## Semantic Review (RAG + LLM)")
        lines.append("")
        if report.review.model_used:
            lines.append(f"*Model: {report.review.model_used} | "
                         f"Tokens: {report.review.prompt_tokens + report.review.completion_tokens:,}*")
            lines.append("")

        for sev in ("ERROR", "WARN", "INFO"):
            rev_findings = [rf for rf in report.review.findings if rf.severity == sev]
            if not rev_findings:
                continue
            lines.append(f"### {sev} ({len(rev_findings)})")
            lines.append("")
            for rf in rev_findings:
                lines.append(f"- **[{rf.check_type}]** {rf.title}")
                lines.append(f"  - {rf.detail}")
                if rf.source_file:
                    lines.append(f"  - Source: `{rf.source_file}`")
            lines.append("")
    elif report.review is None:
        lines.append("## Semantic Review")
        lines.append("")
        lines.append("*Semantic review was not performed.*")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by SDTM RAG Validator*")
    return "\n".join(lines)


def generate_json(report: FullReport) -> dict:
    """Generate a machine-readable JSON validation report."""
    d: dict = {
        "domain": report.domain,
        "file_path": report.file_path,
        "row_count": report.row_count,
        "col_count": report.col_count,
        "completeness_pct": report.completeness_pct,
        "verdict": report.verdict,
        "total_errors": report.total_errors,
        "total_warnings": report.total_warnings,
        "total_info": report.total_info,
        "generated_at": report.generated_at,
        "validation": report.validation.to_dict(),
    }
    if report.review:
        d["review"] = report.review.to_dict()
    return d


def generate_json_str(report: FullReport) -> str:
    return json.dumps(generate_json(report), indent=2, ensure_ascii=False)


def generate_study_json(datasets: list[FullReport], graph_findings: list[Finding]) -> dict:
    """Aggregate per-domain FullReports + cross-domain graph findings into one
    study-level JSON. graph_findings are advisory (WARN/INFO); study_verdict is the
    worst-of per-dataset verdict combined with graph severities."""
    g_err = sum(1 for f in graph_findings if f.severity == "ERROR")
    g_warn = sum(1 for f in graph_findings if f.severity == "WARN")
    g_info = sum(1 for f in graph_findings if f.severity == "INFO")
    total_errors = sum(d.total_errors for d in datasets) + g_err
    total_warnings = sum(d.total_warnings for d in datasets) + g_warn
    total_info = sum(d.total_info for d in datasets) + g_info
    if total_errors:
        verdict = "FAIL"
    elif total_warnings:
        verdict = "PASS_WITH_WARNINGS"
    else:
        verdict = "PASS"
    return {
        "study_verdict": verdict,
        "n_datasets": len(datasets),
        "domains": [d.domain for d in datasets],
        "total_errors": total_errors,
        "total_warnings": total_warnings,
        "total_info": total_info,
        "datasets": [generate_json(d) for d in datasets],
        "graph_findings": [f.to_dict() for f in graph_findings],
    }
