#!/usr/bin/env python3
"""Rebuild output_v2/02_chapters.md with full chapter contents (SDTM Phase 6.5 v2 Task C1).

Unlike the v1 compressed variant (~2180 lines; prose/examples/legalese stripped),
v2.1 preserves the full source of six chapters in their original order.

Algorithm: see `evidence_v2/subagent_prompts/C1_executor.md` (§Algorithm).

Read-only for `knowledge_base/`; overwrites `output_v2/02_chapters.md`.
Idempotent from the second line onward (only the ISO-ts header line varies).
"""
from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

import tiktoken

REPO_ROOT = Path(__file__).resolve().parents[3]
KB_CHAPTERS = REPO_ROOT / "knowledge_base" / "chapters"
OUTPUT_PATH = REPO_ROOT / "ai_platforms" / "claude_projects" / "output_v2" / "02_chapters.md"

# Ordered list of (source_filename, relative_source_path_for_comment)
CHAPTERS: list[tuple[str, str]] = [
    ("ch01_introduction.md", "knowledge_base/chapters/ch01_introduction.md"),
    ("ch02_fundamentals.md", "knowledge_base/chapters/ch02_fundamentals.md"),
    ("ch03_submitting_data.md", "knowledge_base/chapters/ch03_submitting_data.md"),
    ("ch04_general_assumptions.md", "knowledge_base/chapters/ch04_general_assumptions.md"),
    ("ch08_relationships.md", "knowledge_base/chapters/ch08_relationships.md"),
    ("ch10_appendices.md", "knowledge_base/chapters/ch10_appendices.md"),
]

INTRO_BLURB = (
    "This file is the v2 full-expansion of the SDTMIG v3.4 chapters. It reverses the v1 "
    "compression (which dropped prose/examples/legalese and kept only Spec tables plus "
    "numbering rules); every chapter below is the unmodified source from `knowledge_base/chapters/`."
)

SOFT_TARGET = 90_000
HARD_CAP = 110_000

ENCODING_NAME = "cl100k_base"


def _iso_utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_body() -> str:
    """Assemble everything from line 3 onward (the stable portion)."""
    parts: list[str] = []
    parts.append("# SDTMIG v3.4 - Chapters (v2 Full)")
    parts.append("")
    parts.append(INTRO_BLURB)
    parts.append("")

    for idx, (filename, rel_path) in enumerate(CHAPTERS):
        src = KB_CHAPTERS / filename
        if not src.is_file():
            raise FileNotFoundError(f"missing source chapter: {src}")
        content = src.read_text(encoding="utf-8", errors="strict")
        # Strip a single trailing newline so we control spacing; original content preserved byte-for-byte otherwise.
        content_stripped = content.rstrip("\n")
        if idx > 0:
            parts.append("---")
            parts.append("")
        parts.append(f"<!-- source: {rel_path} -->")
        parts.append(content_stripped)
        parts.append("")  # ensure blank line after chapter block

    # Join with \n; build_body is the stable region (from line 3 onward of file).
    body = "\n".join(parts)
    if not body.endswith("\n"):
        body += "\n"
    return body


def main() -> int:
    ts_line = f"<!-- generated by scripts_v2/rebuild_chapters_full.py at {_iso_utc_now()} -->"
    body = build_body()
    # File layout: line1=ts comment, line2=blank, line3+=body (starts with `# SDTMIG ...`)
    full_text = f"{ts_line}\n\n{body}"

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(full_text, encoding="utf-8")

    encoder = tiktoken.get_encoding(ENCODING_NAME)
    token_count = len(encoder.encode(full_text))

    print(
        f"[C1 DONE] 02_chapters.md: {token_count} tokens "
        f"(target <={SOFT_TARGET // 1000}K, hard_cap {HARD_CAP // 1000}K)"
    )
    if token_count > HARD_CAP:
        print(f"[C1 WARN] tokens {token_count} over hard_cap {HARD_CAP // 1000}K")
    return 0


if __name__ == "__main__":
    sys.exit(main())
