#!/usr/bin/env python3
"""Compress knowledge_base/INDEX.md for Claude Projects (Phase 6.5 Step 2).

Reads the 5k-token INDEX.md and emits a compact routing skeleton
(~3k tokens target) at ai_platforms/claude_projects/output/01_index.md.

Compression strategy (per PLAN §4.3):
- Drop table syntax / alignment rows / visual dividers.
- Collapse three-column domain tables to one-line entries: CODE - Name.
- Keep all 9 file-class paths + top-level directories (routing skeleton).
- Keep short one-line description per partition; remove verbose prose.
- Keep VARIABLE_INDEX / ROUTING entry hints.

Source is read-only (P5). Output is deterministic (P7: idempotent).
"""
from __future__ import annotations

import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "knowledge_base" / "INDEX.md"
OUT = ROOT / "ai_platforms" / "claude_projects" / "output" / "01_index.md"
SRC_REL = "knowledge_base/INDEX.md"

# Group label -> list[(code, name)] parsed from source tables.
DOMAIN_GROUPS = [
    "Special-purpose Domains",
    "Interventions Domains",
    "Events Domains",
    "Findings Domains",
    "Trial Design Domains",
    "Relationship Domains",
    "Study Reference Domains",
]

# Short labels in output (keep Claude routing concise).
GROUP_SHORT = {
    "Special-purpose Domains": "Special-purpose",
    "Interventions Domains": "Interventions",
    "Events Domains": "Events",
    "Findings Domains": "Findings",
    "Trial Design Domains": "Trial Design",
    "Relationship Domains": "Relationship",
    "Study Reference Domains": "Study Reference",
}


def parse_domain_tables(text: str) -> dict[str, list[tuple[str, str]]]:
    """Extract (code, name) pairs for each domain group heading."""
    groups: dict[str, list[tuple[str, str]]] = {g: [] for g in DOMAIN_GROUPS}
    current: str | None = None
    # Matches a table row starting with a [CODE](...) link.
    row_re = re.compile(r"^\|\s*\[([A-Z]+)\]\([^)]+\)\s*\|\s*([^|]+?)\s*\|")
    for line in text.splitlines():
        m_h = re.match(r"^###\s+(.+?)\s*$", line)
        if m_h:
            heading = m_h.group(1).strip()
            current = heading if heading in groups else None
            continue
        if current is None:
            continue
        m = row_re.match(line)
        if m:
            code, name = m.group(1), m.group(2).strip()
            groups[current].append((code, name))
    return groups


def build_output(src_text: str) -> str:
    groups = parse_domain_tables(src_text)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines: list[str] = []
    lines.append(f"<!-- generated by scripts/compress_index.py at {timestamp} -->")
    lines.append(f"<!-- source: {SRC_REL} -->")
    lines.append("")
    lines.append("# SDTM Knowledge Base - Routing Index")
    lines.append("")
    lines.append(
        "293 files from SDTM v2.0 + SDTMIG v3.4 (63 domains x 3 + 91 terminology + 6 model + 6 chapters + index)."
    )
    lines.append("")
    lines.append("## Entry Points")
    lines.append("- `ROUTING.md` - question-type router (AI first stop)")
    lines.append(
        "- `VARIABLE_INDEX.md` - reverse index of 1,523 variables (variable -> domain + CT refs)"
    )
    lines.append("")
    lines.append("## Model (SDTM v2.0, `model/`)")
    lines.append(
        "- `01_concepts_and_terms.md` - Ch2: variable roles, qualifier subclasses, table structure"
    )
    lines.append(
        "- `02_observation_classes.md` - Ch3.1: Interventions / Events / Findings / Identifiers / Timing"
    )
    lines.append(
        "- `03_special_purpose_domains.md` - Ch3.2: DM, CO, SE, SJ, SV, SM"
    )
    lines.append(
        "- `04_associated_persons.md` - Ch4: AP rules (APID/RSUBJID/RDEVID/SREL)"
    )
    lines.append(
        "- `05_study_level_data.md` - Ch5: Trial Design (TE/TA/TX/TT/TP/TV/TD/TM/TI/TS/AC) + Study Refs (DI/OI)"
    )
    lines.append(
        "- `06_relationship_datasets.md` - Ch6: RELREC, SUPP--, POOLDEF, RELSUB, DR, APRELSUB, RELSPEC"
    )
    lines.append("")
    lines.append("## Chapters (SDTMIG v3.4, `chapters/`)")
    lines.append("- `ch01_introduction.md` - purpose, organization, changes from v3.3")
    lines.append(
        "- `ch02_fundamentals.md` - observations, variables, domains, GOC, new domains, disallowed vars"
    )
    lines.append(
        "- `ch03_submitting_data.md` - standard/dataset metadata, primary keys, value-level metadata"
    )
    lines.append(
        "- `ch04_general_assumptions.md` - domain/variable/coding/timing/other assumptions"
    )
    lines.append(
        "- `ch08_relationships.md` - GRPID, RELREC, SUPP--, comments, data placement, RELSUB, RELSPEC"
    )
    lines.append(
        "- `ch10_appendices.md` - glossary, controlled terminology, QNAM codes, naming, revision history"
    )
    lines.append("")
    lines.append("## Domains (`domains/<CODE>/`)")
    lines.append(
        "Each domain dir has 3 files: `spec.md` (variable table), `assumptions.md` (business rules), `examples.md` (data samples)."
    )
    lines.append("")
    for group in DOMAIN_GROUPS:
        pairs = groups.get(group, [])
        if not pairs:
            continue
        short = GROUP_SHORT.get(group, group)
        codes_part = ", ".join(f"{code} ({name})" for code, name in pairs)
        lines.append(f"- **{short}** ({len(pairs)}): {codes_part}")
    lines.append("")
    lines.append("## Terminology (`terminology/`)")
    lines.append(
        "Controlled terminology from SDTM Terminology.xlsx (1,005 codelists, 37,939 terms)."
    )
    lines.append("")
    lines.append("### Core (`terminology/core/`, 42 files)")
    lines.append("- `ae.md` - Adverse Events")
    lines.append("- `cp_part1.md`, `cp_part2.md` - Cell Phenotyping")
    lines.append("- `disposition.md` - Disposition")
    lines.append("- `dm.md` - Demographics")
    lines.append("- `eg_part1.md` - `eg_part3.md` - ECG")
    lines.append("- `findings_about.md` - Findings About")
    lines.append("- `general_part1.md` - `general_part5.md` - cross-domain general")
    lines.append("- `gf.md` - Genomics Findings")
    lines.append("- `interventions.md` - Interventions")
    lines.append("- `is_domain_part1.md`, `is_domain_part2.md` - Immunogenicity")
    lines.append("- `lb_part1.md` - `lb_part4.md` - Laboratory")
    lines.append("- `mi.md` - Microscopic Findings")
    lines.append("- `microbiology_part1.md` - `microbiology_part3.md` - Microbiology")
    lines.append("- `oi.md` - Non-host Organism")
    lines.append("- `oncology_part1.md`, `oncology_part2.md` - Oncology (TU/TR/RS)")
    lines.append(
        "- `other_part1.md` - `other_part5.md` - CV, MK, NV, OE, PE, RE, RP, SC, SR, SS, UR"
    )
    lines.append("- `pk_part1.md` - `pk_part4.md` - Pharmacokinetics")
    lines.append("- `qs_part1.md` - Questionnaires core")
    lines.append("- `special_purpose.md` - special-purpose domains")
    lines.append("- `trial_design.md` - Trial Design")
    lines.append("- `vs.md` - Vital Signs")
    lines.append("")
    lines.append("### Questionnaires (`terminology/questionnaires/`, 43 files)")
    lines.append(
        "`questionnaires_part1.md` - `questionnaires_part43.md` - 670 instrument codelists (BDI-II, ADAS-COG, HAM-D, BPI, EORTC, SF-36, UPDRS, etc.)"
    )
    lines.append("")
    lines.append("### Supplementary (`terminology/supplementary/`, 6 files)")
    lines.append(
        "`supplementary_part1.md` - `supplementary_part6.md` - 188 specialized codelists"
    )
    lines.append("")
    lines.append("## Source Documents")
    lines.append("- SDTM v2.0 Final (2021-11-29), 74 pages")
    lines.append("- SDTMIG v3.4, 461 pages")
    lines.append("- SDTMIG v3.4 xlsx - 63 domain specifications")
    lines.append("- SDTM Terminology xlsx - 1,005 codelists / 37,939 terms")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not SRC.is_file():
        print(f"error: source not found: {SRC}", file=sys.stderr)
        return 2
    src_text = SRC.read_text(encoding="utf-8")
    output = build_output(src_text)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(output, encoding="utf-8")
    print(f"wrote {OUT} ({len(output)} chars, {len(output.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
