#!/usr/bin/env python3
"""Merge knowledge_base/model/*.md for Claude Projects (Phase 6.5 Step 4).

Concatenates all 6 model files in order (01-06) with minimal processing
into ai_platforms/claude_projects/output/03_model.md.

Strategy (per PLAN.md §3.2 D9): preserve verbatim (~17K tokens, no compression
needed). Each file is preceded by a <!-- source: ... --> comment. Runs of more
than 2 consecutive blank lines are collapsed to 1 blank line.

Idempotence (P7):
- Timestamp in the generated header is derived from max(mtime) of the sources,
  not from datetime.now(), so running the script twice produces a byte-
  identical file. Source files are read-only (P5).
"""
from __future__ import annotations

import datetime as _dt
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC_DIR = ROOT / "knowledge_base" / "model"
OUT = ROOT / "ai_platforms" / "claude_projects" / "output" / "03_model.md"

MODEL_FILES = [
    "01_concepts_and_terms.md",
    "02_observation_classes.md",
    "03_special_purpose_domains.md",
    "04_associated_persons.md",
    "05_study_level_data.md",
    "06_relationship_datasets.md",
]

_MULTI_BLANK_RE = re.compile(r"\n{3,}")


def _collapse_blanks(text: str) -> str:
    """Collapse runs of >2 consecutive blank lines to a single blank line."""
    return _MULTI_BLANK_RE.sub("\n\n", text)


def main() -> int:
    src_paths = [SRC_DIR / f for f in MODEL_FILES]

    missing = [p for p in src_paths if not p.is_file()]
    if missing:
        for p in missing:
            print(f"error: source not found: {p}", file=sys.stderr)
        return 2

    # Idempotence anchor: max mtime across sources (not datetime.now()).
    max_mtime = max(os.path.getmtime(p) for p in src_paths)
    ts = _dt.datetime.utcfromtimestamp(max_mtime).strftime("%Y-%m-%d %H:%M")

    parts: list[str] = []
    parts.append(
        f"<!-- generated by scripts/merge_model.py (source mtime: {ts}) -->"
    )
    parts.append("")
    parts.append("# SDTM v2.0 Model Reference")
    parts.append("")

    for fname, path in zip(MODEL_FILES, src_paths):
        rel = f"knowledge_base/model/{fname}"
        content = path.read_text(encoding="utf-8")
        content = _collapse_blanks(content).strip()
        parts.append(f"<!-- source: {rel} -->")
        parts.append(content)
        parts.append("")

    output = "\n".join(parts)
    # Final pass: collapse any multi-blanks introduced at section boundaries.
    output = _collapse_blanks(output)
    if not output.endswith("\n"):
        output += "\n"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(output, encoding="utf-8")
    print(f"wrote {OUT} ({len(output)} chars, {len(output.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
