#!/usr/bin/env python3
"""P3 — Generate p3_report.md with gate verification statistics.

Reads p3_candidates.jsonl and writes evidence/checkpoints/p3_report.md.
"""
import json
import statistics
from collections import Counter
from pathlib import Path

BASE = Path(__file__).parent
CANDIDATES = BASE / "p3_candidates.jsonl"
REPORT_DIR = BASE / "evidence" / "checkpoints"
REPORT = REPORT_DIR / "p3_report.md"


def load_jsonl(path: Path) -> list:
    with open(path) as f:
        return [json.loads(line) for line in f if line.strip()]


def pct(lst: list, p: int) -> float:
    if not lst:
        return 0.0
    s = sorted(lst)
    idx = max(0, min(int(len(s) * p / 100), len(s) - 1))
    return s[idx]


def main() -> None:
    print(f"Loading {CANDIDATES} …")
    rows = load_jsonl(CANDIDATES)
    total = len(rows)

    zero_rows = [r for r in rows if r["zero_candidate"]]
    nonzero_rows = [r for r in rows if not r["zero_candidate"]]
    zero_rate = len(zero_rows) / total * 100 if total else 0.0

    # Candidate count stats (non-zero rows)
    cand_counts = [r["candidate_count"] for r in nonzero_rows]
    avg_cands = statistics.mean(cand_counts) if cand_counts else 0.0

    # Top-1 score stats
    top1_scores = [r["candidates"][0]["score"] for r in nonzero_rows if r["candidates"]]
    avg_top1 = statistics.mean(top1_scores) if top1_scores else 0.0

    # ── Gate checks ────────────────────────────────────────────────────────
    gate_line_count = total == 12487
    gate_zero_rate = zero_rate < 20.0
    gate_avg_cands = avg_cands >= 2.0
    gate_avg_top1 = avg_top1 >= 0.20
    all_pass = gate_line_count and gate_zero_rate and gate_avg_cands and gate_avg_top1

    # ── Per-atom-type breakdown ────────────────────────────────────────────
    by_type: dict[str, dict] = {}
    for r in rows:
        t = r["pdf_atom_type"]
        if t not in by_type:
            by_type[t] = {"total": 0, "zero": 0, "top1": []}
        by_type[t]["total"] += 1
        if r["zero_candidate"]:
            by_type[t]["zero"] += 1
        elif r["candidates"]:
            by_type[t]["top1"].append(r["candidates"][0]["score"])

    # ── Zero-candidate breakdown ───────────────────────────────────────────
    zero_by_type = Counter(r["pdf_atom_type"] for r in zero_rows)

    # ── Match basis distribution ───────────────────────────────────────────
    basis_counter: Counter = Counter()
    for r in nonzero_rows:
        for c in r["candidates"]:
            b = c.get("match_basis", "")
            if "domain_route" in b:
                basis_counter["domain_route"] += 1
            elif "chapter_route" in b:
                basis_counter["chapter_route"] += 1
            elif "global_figure" in b:
                basis_counter["global_figure"] += 1
            else:
                basis_counter["global_search"] += 1

    # ── Score distribution ─────────────────────────────────────────────────
    all_scores = [c["score"] for r in nonzero_rows for c in r["candidates"]]

    # ── Build report lines ─────────────────────────────────────────────────
    gate_cell = "✅ **ALL PASS**" if all_pass else "❌ **FAIL**"
    lines = [
        "# P3 Candidate Index Report",
        "",
        f"> Generated by `p3_report.py`",
        f"> Source: `p3_candidates.jsonl`",
        "",
        "---",
        "",
        "## Exit Gate Verification",
        "",
        "| Gate Condition | Threshold | Actual | Result |",
        "|---|---|---|---|",
        f"| p3_candidates.jsonl line count | = 12,487 | {total:,} | {'✅ PASS' if gate_line_count else '❌ FAIL'} |",
        f"| zero_candidate rate | < 20% | {zero_rate:.1f}% | {'✅ PASS' if gate_zero_rate else '❌ FAIL'} |",
        f"| avg candidates (non-zero rows) | ≥ 2.0 | {avg_cands:.2f} | {'✅ PASS' if gate_avg_cands else '❌ FAIL'} |",
        f"| top-1 score mean | ≥ 0.20 | {avg_top1:.3f} | {'✅ PASS' if gate_avg_top1 else '❌ FAIL'} |",
        f"| **Overall Gate** | all PASS | — | {gate_cell} |",
        "",
        "---",
        "",
        "## Summary Statistics",
        "",
        f"- **Total rows**: {total:,}",
        f"- **Zero-candidate rows**: {len(zero_rows):,} ({zero_rate:.1f}%)",
        f"- **Non-zero rows**: {len(nonzero_rows):,}",
        f"- **Avg candidates per non-zero row**: {avg_cands:.2f}",
        f"- **Top-1 score mean**: {avg_top1:.3f}",
        "",
        "### Top-1 Score Distribution (non-zero rows)",
        "",
        "| Percentile | Score |",
        "|---|---|",
        f"| P10 | {pct(top1_scores, 10):.3f} |",
        f"| P25 | {pct(top1_scores, 25):.3f} |",
        f"| P50 (median) | {pct(top1_scores, 50):.3f} |",
        f"| P75 | {pct(top1_scores, 75):.3f} |",
        f"| P90 | {pct(top1_scores, 90):.3f} |",
        f"| P99 | {pct(top1_scores, 99):.3f} |",
        "",
        "### All-candidate Score Distribution",
        "",
        "| Percentile | Score |",
        "|---|---|",
        f"| P10 | {pct(all_scores, 10):.3f} |",
        f"| P50 (median) | {pct(all_scores, 50):.3f} |",
        f"| P90 | {pct(all_scores, 90):.3f} |",
        f"| P99 | {pct(all_scores, 99):.3f} |",
        "",
        "---",
        "",
        "## By Atom Type",
        "",
        "| atom_type | total | zero | zero% | avg_top1 |",
        "|---|---|---|---|---|",
    ]

    for t, d in sorted(by_type.items(), key=lambda x: -x[1]["total"]):
        z = d["zero"]
        tot = d["total"]
        zp = z / tot * 100 if tot else 0.0
        at1 = statistics.mean(d["top1"]) if d["top1"] else 0.0
        lines.append(f"| {t} | {tot:,} | {z:,} | {zp:.1f}% | {at1:.3f} |")

    lines += [
        "",
        "---",
        "",
        "## Zero-Candidate Breakdown by Atom Type",
        "",
        "| atom_type | count |",
        "|---|---|",
    ]
    for t, c in zero_by_type.most_common():
        lines.append(f"| {t} | {c:,} |")

    lines += [
        "",
        "---",
        "",
        "## Match Basis Distribution",
        "",
        "| basis | candidate_count |",
        "|---|---|",
    ]
    for b, c in basis_counter.most_common():
        lines.append(f"| {b} | {c:,} |")

    lines += [
        "",
        "---",
        "",
        f"*Gate result: {'ALL PASS ✅' if all_pass else 'FAIL ❌'}*",
        "",
    ]

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    with open(REPORT, "w") as f:
        f.write("\n".join(lines))

    print(f"Report written: {REPORT}")
    print(f"Gate: {'ALL PASS ✅' if all_pass else 'FAIL ❌'}")
    if not all_pass:
        print(f"  line_count : {'PASS' if gate_line_count else 'FAIL'} ({total:,})")
        print(f"  zero_rate  : {'PASS' if gate_zero_rate else 'FAIL'} ({zero_rate:.1f}%)")
        print(f"  avg_cands  : {'PASS' if gate_avg_cands else 'FAIL'} ({avg_cands:.2f})")
        print(f"  avg_top1   : {'PASS' if gate_avg_top1 else 'FAIL'} ({avg_top1:.3f})")


if __name__ == "__main__":
    main()
